# @package _global_

general_training:
  dense_rewards_at_end: false
  entropy_term: "auto"


reward_model: 
  name: 'rewind'
  batch_size: 64
  model_path: CHECKPOINT_PATH
  reward_at_every_step: true
  camera_names: ["image"]


  success_bonus: 64.0

environment:
  is_state_based: false
  reward_image_key: 'image'

# environment:
#   is_state_based: false

# offline_training:
#   offline_training_steps: 1

# data/h5_buffers/updated_trajs/metaworld_traj_15_demos_roboclipv2.h5